#!/bin/zsh

START='http://server.arcgisonline.com/arcgis/rest/services/'
END='/MapServer/tile/'
VR=0.005

makejpg ()    {
    for F in $(find $1/ -type f -name "*png")
    do 
        ls ${F/png/jpg} || (convert $F ${F/png/jpg} && rm $F)
    done
}

makemymap () {
    makejpg world
    makejpg shade

    SKIP=`find $1/ -type f -name "*.jpg" `
    find . -type f -name "*.jpg"|grep -v $1|sed 's/\.\///;s/\//\/\//;s/.*\/\///'|sort -u|while read D
    do 
        echo $SKIP | grep $1/$D && continue 
        mkdir -p $(dirname $1/$D) 
        ls world/$D shade/$D  && convert world/$D shade/$D \
            -compose hardlight -composite \
            $1/$D 
    done
}

gettiles () {
    echo downloadosmtiles.pl --lat=$1 --lon=$2 --zoom=$3 ...
    downloadosmtiles.pl --lat=$1 --lon=$2 --zoom=$3 --destdir=world --baseurl=${START}'World_Imagery'${END} 
    downloadosmtiles.pl --lat=$1 --lon=$2 --zoom=$3 --destdir=shade --baseurl=${START}'Elevation/World_Hillshade_Dark'${END} 
}

getvolcanoes () {
    # All volcanoes in the world
    grep -v  \"  bna/volcano/volcano.bna|awk -F',' '{print $1,$2}'| while read LO LA
    do
        LA1=$(( $LA - $VR ))
        LA2=$(( $LA + $VR ))
        LO1=$(( $LO - $VR ))
        LO2=$(( $LO + $VR ))
        gettiles ${LA1}:${LA2} ${LO1}:${LO2} 7:15
    done
}

# Global coverage
gettiles    -90:90          -180:180       0:6

# All volcanoes in the world 
getvolcanoes

if [ $# -eq 0 ]; then
    # Central America 
    gettiles      7:14           -90:-80       7:9

    # Costa Rica
    gettiles 8.1367:11.0218 -85.7647:-82.6349 10:12

    # El Salvador
    gettiles 13.03:14.37 -90.45:-87.44 10:12
else
    gettiles $@
fi

# Combine tiles in composite images 
makemymap map
